lib/generators/solidus_friendly_promotions/install/templates/initializer.rb

The API for the Menu Item has recently changed in Solidus' `main` branch. This commit makes the initializer work for both APIs.

Initializer: Use new MenuItem API from Solidus 4.2 onwards

---

app/controllers/solidus_friendly_promotions/admin/promotion_actions_controller.rb
app/views/solidus_friendly_promotions/admin/promotion_actions/edit.html.erb

Previously, when changing the promotion calculator type for an action, we would end up with an unrescued 500 error. This implements editing an action.

Promotion Actions: Implement "edit" action

---

app/models/solidus_friendly_promotions/promotion.rb
app/views/solidus_friendly_promotions/admin/promotions/_form.html.erb
config/locales/en.yml
db/migrate/20230928093138_add_lane_to_solidus_friendly_promotions_promotions.rb
spec/models/solidus_friendly_promotions/promotion_spec.rb

This implements the "lane" concept in the simplest way I can imagine: By just adding an enum with sortable values, we can identify the order in which stacked promotions should be applied. We do not need an additional ActiveRecord model that is sortable, as we don't want to burden administrators with creating and maintaining the lanes, and three lanes should be enough.

Add "Lane" enum to Promotion

---

app/decorators/models/solidus_friendly_promotions/order_decorator.rb
spec/models/spree/order_spec.rb

This is the same change as in
https://github.com/solidusio/solidus/pull/5411

Add dependent: :destroy to Spree::Order#friendly_promotions

---

app/views/solidus_friendly_promotions/admin/promotion_actions/calculators/tiered_flat_rate/_fields.html.erb
app/views/solidus_friendly_promotions/admin/promotion_actions/calculators/tiered_percent/_fields.html.erb
app/views/solidus_friendly_promotions/admin/promotion_categories/new.html.erb
app/views/solidus_friendly_promotions/admin/promotion_codes/index.html.erb
app/views/solidus_friendly_promotions/admin/promotion_rules/_type_select.html.erb
app/views/solidus_friendly_promotions/admin/promotion_rules/rules/_product.html.erb
app/views/solidus_friendly_promotions/admin/promotion_rules/rules/_store.html.erb
app/views/solidus_friendly_promotions/admin/promotion_rules/rules/_taxon.html.erb
app/views/solidus_friendly_promotions/admin/promotion_rules/rules/_user.html.erb
app/views/solidus_friendly_promotions/admin/promotion_rules/rules/_user_role.html.erb
app/views/solidus_friendly_promotions/admin/promotions/_form.html.erb
app/views/solidus_friendly_promotions/admin/promotions/index.html.erb
config/locales/en.yml

Prior to this commit, we were still using the translations in core Solidus.

Reference our own I18n namespace in views

---

app/models/solidus_friendly_promotions/promotion.rb
app/models/solidus_friendly_promotions/promotion_action.rb
app/views/solidus_friendly_promotions/admin/promotions/_form.html.erb
config/locales/en.yml
db/migrate/20231006134042_add_customer_label_to_promotions.rb
lib/solidus_friendly_promotions/testing_support/friendly_promotion_factory.rb
spec/models/solidus_friendly_promotions/promotion_action_spec.rb
spec/models/solidus_friendly_promotions/promotion_spec.rb
spec/system/solidus_friendly_promotions/admin/promotions_spec.rb

This adds a "customer_label" column to the promotion model, allowing admins to name their promotions independently of the customer experience.

Customer label

---

app/views/solidus_friendly_promotions/admin/promotions/index.html.erb
app/views/solidus_friendly_promotions/admin/shared/_promotion_sub_menu.html.erb
config/locales/en.yml
lib/generators/solidus_friendly_promotions/install/templates/initializer.rb
lib/solidus_friendly_promotions.rb

Requiring `spree` results in a load error in real life.

Require solidus

---

app/models/solidus_friendly_promotions/rules/product.rb
config/locales/en.yml
spec/models/solidus_friendly_promotions/rules/product_spec.rb

This addition to the order product rule makes the rule match if the order contains exclusively the products specified in the rule.

Add "only" match policy to product rule

---

app/models/solidus_friendly_promotions/permission_sets/friendly_promotion_management.rb
spec/models/solidus_friendly_promotions/permission_sets/friendly_promotion_management.rb

This can be used to allow other roles than admin the ability to manage Friendly Promotions.

Add PermissionSet for Friendly Promotions

---

app/views/solidus_friendly_promotions/admin/shared/_promotion_sub_menu.html.erb

I did this at some point, but it's not in main.

Add links to legacy promotions in Solidus 4.1

---

app/models/solidus_friendly_promotions/rules/line_item_product.rb
app/models/solidus_friendly_promotions/rules/line_item_taxon.rb

This went through the legacy join table, but has to go through the new join table.

Fix class name option in line item taxon association

---

app/views/solidus_friendly_promotions/admin/promotion_actions/_promotion_action.html.erb
app/views/solidus_friendly_promotions/admin/promotion_actions/edit.html.erb
spec/system/solidus_friendly_promotions/admin/promotions_spec.rb

The behaviour of the turbo_frame_tag helper changed in Turbo 1.5 and now does not support passing multiple models. These changes account for the change in output and behaviour.
See https://github.com/hotwired/turbo-rails/pull/476

Fix Turbo frame tags for Turbo 1.5

---

lib/solidus_friendly_promotions/promotion_map.rb
lib/solidus_friendly_promotions/promotion_migrator.rb
lib/tasks/solidus_friendly_promotions/migrate_existing_promotions.rake

This adds a promotion migrator that generates SolidusFriendlyPromotion objects from existing Spree::Promotion objects.
Care has been taken that this can be used in host applications.

Add Promotion Migrator

---

app/decorators/models/solidus_friendly_promotions/adjustment_decorator.rb
app/decorators/models/solidus_friendly_promotions/order_decorator.rb
app/models/solidus_friendly_promotions/order_discounter.rb
spec/models/solidus_friendly_promotions/order_discounter_spec.rb
spec/models/spree/adjustment_spec.rb

This is to support the migration of existing stores. After having migrated the promotion configuration, you can flip the switch, and old promotion system adjustments will be replaced by new promotion system adjustments.

Transparently replace promotion adjustments

---

app/models/solidus_friendly_promotions/promotion.rb
app/models/solidus_friendly_promotions/promotion_action.rb
db/migrate/20231013181921_add_original_promotion_ids.rb
spec/models/solidus_friendly_promotions/promotion_action_spec.rb
spec/models/solidus_friendly_promotions/promotion_spec.rb

During and after migrating promotions from the existing system, it would be nice for troubleshooting and auditing to be able to determine exactly which promotion and action they came from.
https://github.com/friendlycart/solidus_friendly_promotions/issues/33

Add back references to promotions and actions

---

spec/models/solidus_friendly_promotions/promotion_rule_spec.rb

Removes a (legitimate) warning from our spec runs.

Fix spec warning in promotion rules spec

---

lib/solidus_friendly_promotions/promotion_migrator.rb
spec/lib/solidus_friendly_promotions/promotion_migrator_spec.rb

Now that we have associations for the original promotion and original promotion actions, we need to also store them when migrating.
Fixes #33

Migrator: Store original promotion and promotion action

---

lib/solidus_friendly_promotions/promotion_migrator.rb
spec/lib/solidus_friendly_promotions/promotion_migrator_spec.rb

This migrates the promotion codes and promotion code batches from the legacy promotion system to the current promotion system.
Fixes #43

Migrator: Migrate promotion codes and promotion code batches

---

app/models/solidus_friendly_promotions/promotion_rule.rb
config/locales/en.yml

We want to have all the relevant I18n content for promotions in this gem, under our namespace. This commit accomplishes that.

Import eligiblity error messages from Solidus

---

README.md
app/views/solidus_friendly_promotions/admin/promotion_rules/rules/_shipping_method.html.erb

This fixes two instances, one in the README, where we were using the wrong top-level constant.

Fix: SolidusFriendlyPromotions, not Shipping

---

app/models/solidus_friendly_promotions/rules/line_item_product.rb
spec/models/solidus_friendly_promotions/rules/line_item_product_spec.rb

This adds the error messaging capability to the line item products rule. Consider that all errors are on the order level, and that they won't appear if other line items make them irrelevant.

Line Item Product Rule: Add error messaging

---

lib/solidus_friendly_promotions/testing_support/factories/friendly_shipping_rate_discount_factory.rb
spec/lib/solidus_friendly_promotions/testing_support/factories_spec.rb

This factory would violate a not-null constraint.

Fix shipping rate discount factory

---

lib/solidus_friendly_promotions/migrate_adjustments.rb
lib/tasks/solidus_friendly_promotions/migrate_adjustments.rake
spec/lib/solidus_friendly_promotions/migrate_adjustments_spec.rb

Also has a task to migrate back.

Add a rake task to migrate adjustments from legacy promotions

---

app/decorators/models/solidus_friendly_promotions/order_decorator.rb
spec/models/spree/order_spec.rb

SolidusFriendlyPromotions does not need this call, and it could be actively harmful if SFP is active.

Do not call Spree::PromotionHandler::Shipping when SFP is active

---

app/models/solidus_friendly_promotions/promotion_code/batch_builder.rb
spec/models/solidus_friendly_promotions/promotion_code/batch_builder_spec.rb

Backport Solidus PR 5383 with PR description:
When a new promotion with 2.5m new promo codes has created, it just generated about 250k promo codes and then stopped.
The PromotionBatch screen this error: Errored: #<ActiveRecord::RecordInvalid: Validation failed: Value has already been taken>
This PR rescues the exception raised by the Spree::PromotionCode creation and jumps to the next code to save, avoiding stopping the process completely. The PR also adds the ability to restart the PromotionCodeBatch from the latest PromotionCodes created.
Cf https://github.com/solidusio/solidus/pull/5383

Backport promotion code batch fix from Solidus

---

lib/solidus_friendly_promotions/promotion_migrator.rb
spec/lib/solidus_friendly_promotions/promotion_migrator_spec.rb

If the promotion migrator's promotion map does not include the promotion actions or rules from the original Spree promotions, don't fail with an error, and still create all the promotions.

Promo Migrator: Ignore missing rules and actions

---

app/models/solidus_friendly_promotions/promotion.rb
spec/models/solidus_friendly_promotions/promotion_spec.rb

This is necessary to be able to delete promotions.

Add missing relation: SolidusFriendlyPromotions#order_promotions

---

MIGRATING.md
lib/solidus_friendly_promotions/migrate_order_promotions.rb
lib/tasks/solidus_friendly_promotions/migrate_order_promotions.rake
spec/lib/solidus_friendly_promotions/migrate_order_promotions_spec.rb

There is code to migrate promotions on the fly and create these automatically. However, it will be nice to eventually remove all of the old promotions and all of their references.
Co-Authored-By: mamhoff@gmail.com

Add migrate order promotions rake task

---

app/models/solidus_friendly_promotions/actions/adjust_line_item.rb
app/models/solidus_friendly_promotions/actions/adjust_shipment.rb
app/models/solidus_friendly_promotions/calculators/distributed_amount.rb
app/models/solidus_friendly_promotions/eligibility_result.rb
app/models/solidus_friendly_promotions/eligibility_results.rb
app/models/solidus_friendly_promotions/friendly_promotion_discounter.rb
app/models/solidus_friendly_promotions/item_discounter.rb
app/models/solidus_friendly_promotions/order_discounter.rb
app/models/solidus_friendly_promotions/promotion.rb
app/models/solidus_friendly_promotions/promotion_action.rb
app/models/solidus_friendly_promotions/promotion_eligibility.rb
app/models/solidus_friendly_promotions/promotion_handler/coupon.rb
app/models/solidus_friendly_promotions/promotions_eligibility.rb
config/locales/en.yml
spec/models/solidus_friendly_promotions/actions/adjust_line_item_spec.rb
spec/models/solidus_friendly_promotions/actions/adjust_shipment_spec.rb
spec/models/solidus_friendly_promotions/eligibility_result_spec.rb
spec/models/solidus_friendly_promotions/eligibility_results_spec.rb
spec/models/solidus_friendly_promotions/friendly_promotion_discounter_spec.rb
spec/models/solidus_friendly_promotions/promotion_action_spec.rb
spec/models/solidus_friendly_promotions/promotion_handler/coupon_spec.rb

This is the service object that deals with a coupon code being added to the order while in checkout. It checks the coupon code's promotion's eligibility and, depending on eligibilty, connects it to the order or not.
This is where we use the eligibility results class, and I'm not sure I'm loving the API. I think we want to iterate on that for a bit more.

Add a PromotionHandler::Coupon

---

lib/solidus_friendly_promotions/migrate_order_promotions.rb
spec/lib/solidus_friendly_promotions/migrate_order_promotions_spec.rb

Adds a specs for order promotions without promotion codes as well as speeds the whole thing up using SQL magic.

Refactor order promotions migrator

---

app/models/solidus_friendly_promotions/friendly_promotion_discounter.rb
spec/models/solidus_friendly_promotions/friendly_promotion_discounter_spec.rb

If a shipping rate happens to have a nil cost, then don't try to create a discount for it.

Ignore shipping rates that have no cost

---

app/models/solidus_friendly_promotions/friendly_promotion_discounter.rb
app/models/solidus_friendly_promotions/order_discounter.rb
app/models/solidus_friendly_promotions/promotion_action.rb
spec/models/solidus_friendly_promotions/order_discounter_spec.rb
spec/models/solidus_friendly_promotions/promotion_action_spec.rb

The specs here are a bit contrived, as it's unlikely for a calculator to have a zero percentage. However, the scenario is quite real: In shops that don't select a shipping rate automatically in the delivery step of checkout, the shipment's cost will be zero until the customer has selected a shipping rate. At this point the promotion system will happily add discounts with no amount.

Never create adjustments with a zero amount

---

app/models/solidus_friendly_promotions/promotion_handler/page.rb
spec/models/solidus_friendly_promotions/promotion_handler/page_spec.rb

This is modeled after `Spree::PromotionHandler::Page`. One could add error handling like in the
`SolidusFriendlyPromotions::PromotionHandler::Coupon`, but that is not implemented the base version either.

Add PromotionHandler::Page

---

spec/models/solidus_friendly_promotions/order_discounter_spec.rb

We've refactored `call` out of the subject, but this PR did not know about that.

Fix order discounter spec

---

Rakefile

This is to allow us to release versions in a simple, standard-compliant fashion.

Add bundler/gem_tasks

---

app/models/solidus_friendly_promotions/promotion_handler/null.rb
spec/models/solidus_friendly_promotions/promotion_handler/null_spec.rb

This class is useful for satisfying Solidus' need for a shipping promotion handler. With SolidusFriendlyPromotions, shipping promotions are handled just like other promotions, so we don't need to do anything here.
See https://github.com/solidusio/solidus/pull/5466

Add a null promotion handler

---

lib/generators/solidus_friendly_promotions/install/templates/initializer.rb

Solidus 2.4 introduced a new admin navbar with new icons that can be enabled in the settings. Adopt to that.

Use Remix icons if Solidus' admin_updated_navbar is enabled

---

spec/models/solidus_friendly_promotions/promotion_handler/coupon_spec.rb

Promotion Rules are not ordered, so the database might return them in any order. This adjusts the spec accordingly (especially Postgres returns them in a different order than expected sometimes).
See https://app.circleci.com/pipelines/github/friendlycart/solidus_friendly_promotions/295/workflows/f5d74528-a1f5-4ec8-9eb1-3cf7deda4d2d/jobs/957

Coupon Promo Handler: Fix flaky spec

---

app/models/solidus_friendly_promotions/actions/adjust_line_item_quantity_groups.rb
app/models/solidus_friendly_promotions/calculators/distributed_amount.rb
app/models/solidus_friendly_promotions/promotion.rb
app/models/solidus_friendly_promotions/rules/minimum_quantity.rb

There are now three spots in this code base that need a method to collect the line items that pass all applicable rules for an order and can be discounted. Time to extract.

Refactor: Extract `Promotion#applicable_line_items`

---

app/decorators/models/solidus_friendly_promotions/line_item_decorator.rb
app/models/solidus_friendly_promotions/actions/create_discounted_item.rb
app/views/solidus_friendly_promotions/admin/promotion_actions/actions/_create_discounted_item.html.erb
config/locales/en.yml
spec/models/promotion/integration_spec.rb

This adds functionality to `CreateDiscountedItems` to become the full "Buy X get Y free" promotion. In the process, we add a way to change quantities from with the managing promotion action to managed line items.

Allow changing quantity for automatic line items

---

app/models/concerns/solidus_friendly_promotions/calculators/promotion_calculator.rb
app/models/solidus_friendly_promotions/calculators/distributed_amount.rb
app/models/solidus_friendly_promotions/calculators/flat_rate.rb
app/models/solidus_friendly_promotions/calculators/flexi_rate.rb
app/models/solidus_friendly_promotions/calculators/percent.rb
app/models/solidus_friendly_promotions/calculators/tiered_flat_rate.rb
app/models/solidus_friendly_promotions/calculators/tiered_percent.rb
app/models/solidus_friendly_promotions/calculators/tiered_percent_on_eligible_item_quantity.rb
app/views/solidus_friendly_promotions/admin/promotion_actions/actions/_calculator_fields.erb
app/views/solidus_friendly_promotions/admin/promotion_actions/calculators/tiered_flat_rate/_fields.html.erb
app/views/solidus_friendly_promotions/admin/promotion_actions/calculators/tiered_percent/_fields.html.erb
app/views/solidus_friendly_promotions/admin/promotion_actions/calculators/tiered_percent_on_eligible_item_quantity/_fields.html.erb
app/views/solidus_friendly_promotions/admin/promotion_actions/calculators/tiered_percent_on_eligible_item_quantity/_tier_fields.html.erb
config/locales/en.yml
lib/generators/solidus_friendly_promotions/install/templates/initializer.rb
spec/models/solidus_friendly_promotions/calculators/tiered_percent_on_eligible_item_quantity_spec.rb

This does a bit of calculator refactoring to show us what calculators do, but the big change here is a calculator that can give us tiered discount based on how many matching items the customer has in their cart.

Tiered calculators

---

app/views/solidus_friendly_promotions/admin/shared/_promotion_sub_menu.html.erb

This condition
```RUBY
can? :admin, Spree::Promotion && Spree::Promotion.any?
```
Interprets as
```RUBY
can? :admin, (Spree::Promotion && Spree::Promotion.any?) # =>
can? :admin, [false/true] # => always true for admin =>  
```

Fix admin sub menu entry visibility condition

---

app/controllers/solidus_friendly_promotions/admin/base_controller.rb
app/controllers/solidus_friendly_promotions/admin/promotion_rules_controller.rb
app/helpers/solidus_friendly_promotions/admin/promotion_rules_helper.rb
app/models/concerns/solidus_friendly_promotions/rules/line_item_applicable_order_rule.rb
lib/solidus_friendly_promotions/promotion_migrator.rb

New standard version, new rules, new fixes.

Fix standardrb violations

---

app/models/solidus_friendly_promotions/friendly_promotion_adjuster.rb
lib/solidus_friendly_promotions/configuration.rb
spec/lib/solidus_friendly_promotions/configuration_spec.rb
spec/models/solidus_friendly_promotions/friendly_promotion_adjuster_spec.rb

This gem allows recalculating complete orders until they are shipped, because Solidus allows changing an order's contents until the order is shipped.
This change adds a configuration option that disables the recalculation of orders after they are completed. Some shops make changes to existing promotions, and expect that this does not change complete, but unshipped orders.

Add configuration option: `recalculate_complete_orders`

---

app/models/solidus_friendly_promotions.rb
config/initializers/solidus_friendly_promotions.rb
lib/solidus_friendly_promotions.rb

In Rails 7.1.3, the `table_name_prefix` method is redefined if it is not already defined. Since we have multiple module definitions, we need to make sure that the class method is defined before we load `engine.rb`.

Define SolidusFriendlyPromotions.table_name_prefix early

---

app/controllers/solidus_friendly_promotions/admin/promotion_actions_controller.rb
app/models/solidus_friendly_promotions/promotion.rb
app/models/solidus_friendly_promotions/promotion_action.rb
app/views/solidus_friendly_promotions/admin/promotions/_table.html.erb
app/views/solidus_friendly_promotions/admin/promotions/_table_filter.html.erb
bin/sandbox
config/locales/en.yml
db/migrate/20240124104855_add_deleted_at_to_promotions.rb
db/migrate/20240125102050_drop_deleted_at_from_promotion_actions.rb
spec/models/solidus_friendly_promotions/friendly_promotion_adjuster/load_promotions_spec.rb
spec/models/solidus_friendly_promotions/promotion_action_spec.rb
spec/models/solidus_friendly_promotions/promotion_spec.rb

Prior to this PR, soft deletion was implemented for the `SolidusFriendlyPromotion::PromotionAction`. However, there was no UI making soft-deleted records visible, and it appears this was only done so that `Spree::Adjustment` records never lose their source. 
This PR moves the soft-deletion faculty to the `SolidusFriendlyPromotion::Promotion` model, adds a little bit of UI to make them visible if necessary, and tells the `Spree::PromotionAction` model how to deal with adjustments: If there's adjustments where the order is complete, refuse to be deleted, if there's adjustments where the order is incomplete, delete those adjustments. 
Fixes #30

Improve soft-deletion faculty

---

Gemfile

SQLite 2.0 has recently been released, but the Rails/Solidus ecosystem isn't quite there yet.

Restrict SQLite to "~> 1.3"

---

app/models/solidus_friendly_promotions/promotion_action.rb
app/models/solidus_friendly_promotions/shipping_rate_discount.rb
spec/models/solidus_friendly_promotions/promotion_action_spec.rb
spec/models/solidus_friendly_promotions/shipping_rate_discount_spec.rb

Promotion actions are not soft-deletable anymore.
Fixes #105

Fix ShippingRateDiscount#promotion_action

---

.circleci/config.yml
Gemfile
spec/spec_helper.rb

The production code would still run with Ruby 3.0, but the test suite will use a version of Rails that doesn't play well with the current `selenium-webdrivers` gem. Moving the Ruby versions up by a minor version fixes the test suite.

Fix selenium path

---

app/models/solidus_friendly_promotions/promotion_rule.rb
config/locales/en.yml
spec/models/solidus_friendly_promotions/friendly_promotion_adjuster/discount_order_spec.rb
spec/models/solidus_friendly_promotions/promotion_rule_spec.rb

This used outdated syntax that did not actually work, and the spec indicated invalidity because of the promotion with ID = 1 not existing.
Now we create a real promotion to test with, and we add the error in the correct way. As a bonus, we use I18n for the error message.

Fix Promotion Rule Unique per promotion validation

---

app/models/solidus_friendly_promotions/promotion_advertiser.rb
lib/solidus_friendly_promotions/configuration.rb
spec/lib/solidus_friendly_promotions/configuration_spec.rb
spec/models/solidus_friendly_promotions/promotion_advertiser_spec.rb

In https://github.com/solidusio/solidus/pull/5739, Solidus introduces a promotion advertiser class. 
This implements that configuration endpoint for this gem.

Promotion advertiser

---

app/models/solidus_friendly_promotions/friendly_promotion_adjuster/load_promotions.rb
app/models/solidus_friendly_promotions/order_promotion.rb
app/models/solidus_friendly_promotions/promotion.rb
app/models/solidus_friendly_promotions/promotion_code.rb
spec/models/solidus_friendly_promotions/promotion_spec.rb

When applying or validating a promotion, we load all associated promotions through order_promotions and check their usage limit. A discarded promotion can still be associated with an order. If we do not load discarded promotions, then the order_promotion will not have an associated promotion and checking usage limits will result in an error.

Include Discarded Promotions

---

.circleci/config.yml

3.3.3 has weird issues, see https://stackoverflow.com/questions/78617432/strange-bundle-update-issue-disappearing-net-pop-0-1-2-dependency

Only build on Ruby 3.3.2 for now

---

app/jobs/solidus_friendly_promotions/promotion_code_batch_job.rb
spec/models/solidus_friendly_promotions/promotion_code/batch_builder_spec.rb
spec/requests/solidus_friendly_promotions/admin/benefits_request_spec.rb
spec/requests/solidus_friendly_promotions/admin/conditions_request_spec.rb
spec/system/solidus_friendly_promotions/admin/promotion_categories_spec.rb
spec/system/solidus_friendly_promotions/admin/promotion_code_batches_spec.rb

This fixes a bunch of specs that only work because certain conditions are true: 
- we allow RSpec's DSL in the root namespace, even though we didn't do that at the very beginning. Add `RSpec.` for clarity.
- in some specs we used objects of the legacy promotions gem. We obviously want to test/mock our own code. 
- A `standardrb --fix` has made a job inherit from `ApplicationJob` even though we don't have `ApplicationJob` as this is a library.

Miscellaneous spec fixes

---

solidus_friendly_promotions.gemspec
spec/spec_helper.rb

This extension is mostly compatible with Turbo 2. However, Turbo 2 references ActionCable in its `app/channels` folder, and that breaks eager loading for our dummy app (which doesn't have ActionCable).

Allow Turbo 2.x, but fix its issues

---

Rakefile
solidus_friendly_promotions.gemspec
spec/rails_helper.rb
spec/spec_helper.rb

This changes the spec setup to use the `DummyApp` that Solidus core provides. This makes testing easier and faster, and it also mirrors the setup of the gems within the `solidusio/solidus` repository. Since we want to integrate this gem there soon, it makes sense to already mirror the structures needed there. 
This includes the work from #123 , #122, and #121.

Use single-file dummy app from Solidus core

---

db/migrate/20231013181921_add_original_promotion_ids.rb

If this is a vanilla install, we cannot make a foreign key constraint to the `spree_promotions` table as it is not present.

Only add foreign key if necessary

---

lib/solidus_friendly_promotions/testing_support/factory_bot.rb
solidus_friendly_promotions.gemspec
spec/rails_helper.rb

This adds a `solidus_friendly_promotions/testing_support/factory_bot` file and drops the dependency on `solidus_dev_support`.

Prepare solidus integration
